apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-install
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dougdalo/kafka-strimzi-lab
    targetRevision: main
    path: install
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
