apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-connect-scaledobject
  namespace: kafka
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-connect-connect
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc:9092
        consumerGroup: kafka-connect-cluster
        topic: kafka-connect-offsets
        lagThreshold: "50"
        offsetResetPolicy: latest
